services:
  rl-prompt-optimizer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - WOLFRAM_APP_ID=${WOLFRAM_APP_ID}
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    command: python deployment_server.py
